# AndroidX & Build Flags
android.useAndroidX=true
android.nonTransitiveRClass=true

# JVM Options for fast compilation
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1536m
android.defaults.buildfeatures.resvalues=true
android.builtInKotlin=false
android.newDsl=false

# Suppress transition warnings for AGP 9.x
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
